// react-node-mongo/vue-client/src/components/Task.vue
<template>
    <div :class="{ 'task': true, 'invisible': isDeleted, 'fade-in': !isDeleted }">
      <input type="checkbox" @change="handleCheckboxChange" :checked="task.completed" />
      <p :class="{ 'checked': task.completed }">{{ task.content }}</p>
      <img class="deleteButton" src="@/assets/cross.png" @click="handleDelete" />
    </div>
  </template>
  
  <script setup>
  import { ref, watch, defineProps, defineEmits} from 'vue';
  const props = defineProps(['task', 'onDelete', 'onCompleted']);

  const emits = defineEmits();

  const isDeleted = ref(false);

  const handleCheckboxChange = () => {
        emits('onCompleted', props.task.id);
  };
  
  const handleDelete = () => {
    props.task.deleting = true;
    isDeleted.value = true;

    setTimeout(() => {
      emits('onDelete', props.task.id);
    }, 600);
  };
  
  </script>

// react-node-mongo/client/src/components/Task.js
import React, { useState } from 'react';
import deleteImage from '../assets/cross.png';

function Task({task, onDelete, onCompleted}) {

    const [isDeleted, setIsDeleted] = useState(false);


    const handleCheckboxChange = () => {
        onCompleted(task.id);
      };

    const handleDelete = () => {
        setIsDeleted(true);
        setTimeout(() => {
            onDelete(task.id);
            console.log(task.id);
          }, 600);
    };

    return (
      <div className={"task " + (isDeleted ? "invisible" : "fade-in")} >
        <input type="checkbox" onChange={handleCheckboxChange} checked={task.completed ? "checked" : ""}/>
        <p className={task.completed ? "checked" : ""}>{task.content}</p>
        <img className="deleteButton" src={deleteImage} onClick={handleDelete}/>
    </div>
    );
}

export default Task;
