// react-node-mongo/angular-client/src/app/auth-form/auth-form.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';

import { UserService } from '../user.service'; 
import { HeaderComponent } from '../header/header.component'; // Assuming you have a HeaderComponent to display the header

const backendUrl = 'http://localhost:3001';

@Component({
  selector: 'app-auth-form',
  templateUrl: './auth-form.component.html',
  styleUrls: ['./auth-form.component.css'],
  standalone: true,
  imports: [CommonModule, HeaderComponent],
  providers: [UserService]
})
export class AuthFormComponent {
  login: string = '';
  password: string = '';
  errors = { passwordTooShort: false, passwordInvalid: false };

  constructor(private http: HttpClient, private userService: UserService) {}

  handleInputChange(event: any): void {
    const target = event.target;
    const value = target.value;
    const name = target.name;
  
    (this as any)[name] = value;
    this.errors = { passwordInvalid: false, passwordTooShort: false };
  }

  handleSubmit(event: any): void {
    event.preventDefault();

    const postData: any = {
      login: this.login,
      password: this.password
    };

    if (this.password.length < 4) {
      this.errors = { ...this.errors, passwordTooShort: true };
      return;
    }

    this.http.post<any>(`${backendUrl}/api/users`, postData)
      .subscribe(
        response => {
          this.userService.setUser(response.token, response.login);
          this.userService.setCookie(response.token, response.login);
        },
        error => {
          if (error.status === 401) {
            const data = error.error;
            if (data.error === 'INVALID_PASSWORD') {
              this.errors = { ...this.errors, passwordInvalid: true };
            } else {
              console.error(error);
            }
          }
        }
      );
  }
}

// react-node-mongo/clients/react-client/src/components/AuthForm.js
import { useState, useRef, useEffect } from "react";
import axios from 'axios'
import config from '../config.js'
import Cookies from 'universal-cookie';

const backendUrl = config.backendUrl;

function AuthForm({user, setUser}) {
const [login, setLogin] = useState('');
const [password, setPassword] = useState('');
const [errors, setErrors] = useState({passwordTooShort: false, passwordInvalid : false});

const handleInputChange = (event, setter) =>  {
  setter(event.target.value);
  setErrors({...errors, passwordInvalid:false, passwordTooShort:false});
};

const handleSubmit = (event) => {
  event.preventDefault();

  const postData = {};
  postData.login = login;
  postData.password = password;
  if (password.length < 4) {
    setErrors({...errors, passwordTooShort:true});
    return;
  }
  axios
  .post(backendUrl + '/api/users', postData)
  .then(response => {
    setUser({token: response.data.token, login: response.data.login});
    const cookies = new Cookies();
    cookies.set("jwt-token", response.data.token);
    cookies.set("login", response.data.login);
  })
  .catch(error => {
    if (error.response && error.response.status == 401) {
      const data = error.response.data;
      if (data.error == "INVALID_PASSWORD") {
        setErrors({...errors, passwordInvalid:true});
        }
    else
      console.log(error);
  }});
};

return (
  <div className="authFormComponent">
    <h2>Log in and register</h2>
    <form className="signupForm">
    <input className={errors.passwordInvalid ? "inError" : null} placeholder="Username" onChange={(e) => handleInputChange(e, setLogin)} name="login" />
    <input className={errors.passwordInvalid || errors.passwordTooShort ? "inError" : null} placeholder="Password" onChange={(e) => handleInputChange(e, setPassword)} type='password' name="password" />
    <button label="Sign Up" onClick={handleSubmit} type="submit">Submit</button>
    </form>
    {errors.passwordTooShort && 
  <p className="error">Password needs at least four characters</p>} 
      {errors.passwordInvalid &&
    <p className="error">This username is already in use, or you input the wrong password.</p>
    }
  </div>
)
}

export default AuthForm;
