// clients/angular-client/src/app/new-task-form/new-task-form.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { UserService } from '../user.service'; 
import { TaskListService } from '../task-list.service';

const backendUrl = 'http://localhost:3001';

@Component({
  selector: 'app-new-task-form',
  standalone: true,
  templateUrl: './new-task-form.component.html',
  styleUrls: ['./new-task-form.component.css'],
  providers: [UserService]
})
export class NewTaskFormComponent implements OnInit {
  newTask: string = '';
  @ViewChild('elementRef') elementRef!: ElementRef;

  constructor(private http: HttpClient, private userService: UserService, private taskListService: TaskListService) {}

  ngOnInit(): void {
    console.log('Component rendered');
  }

  handleInputChange(event: Event): void {
    const targetElement = event.target as HTMLElement;
    this.newTask = targetElement.innerText;
  }

  handleSubmit(event: Event): void {
    event.preventDefault();

    if (this.newTask.length === 0) {
      return;
    }

    const postData: any = {
      content: this.newTask
    };

    this.taskListService.addTask(postData);

    this.elementRef.nativeElement.innerHTML = '';
    this.newTask = '';
  }
}

// react-node-mongo/clients/react-client/src/components/NewTaskForm.js
import React, { useState, useRef, useEffect } from 'react';
import axios from 'axios'
import config from '../config.js'

const backendUrl = config.backendUrl;

function NewTaskForm({user, tasks, setTasks}) {
    const [newTask, setNewTask] = useState('')
    const elementRef = useRef(null);


    useEffect(() => {
      console.log('Component rendered');
    }, []);


    const handleInputChange = (event, setter) =>  {
      setter(event.target.innerText);
    };
  
    const handleSubmit = (event) => {
      event.preventDefault();
  
      if (newTask.length == 0)
        return;

      const postData = {};
      postData.content = newTask;
  
      axios
      .post(backendUrl + '/api/tasks', postData,  { headers:{'Authorization': `Bearer ${user.token}` } })
      .then(response => {
        console.log(response)
        setTasks([...tasks, {login:user.login, id:response.data.id, content:postData.content}]);
        elementRef.current.innerHTML = '';
        setNewTask('');
      })
      .catch(error => {
        if (error.response && error.response.status == 500) {
          const data = error.response.data;
        }
      });
      };
  
    return (
    <form id="newTask">
    <div ref={elementRef} className="textarea" contentEditable="true" onInput={(e) => handleInputChange(e, setNewTask)}></div>
    <button label="Task" onClick={handleSubmit} type="submit">ADD</button>
    </form>
    );
  }

  export default NewTaskForm;
