// react-node-mongo/client/src/components/Task.js
import React, { useState } from 'react';
import deleteImage from '../assets/cross.png';

function Task({task, onDelete, onCompleted}) {

    const [isDeleted, setIsDeleted] = useState(false);


    const handleCheckboxChange = () => {
        onCompleted(task.id);
      };

    const handleDelete = () => {
        // mutating state directly to handle rapid deletion
        task.deleting = true;
        setIsDeleted(true);
        setTimeout(() => {
            onDelete(task.id);
            console.log(task.id);
          }, 600);
    };

    return (
      <div className={"task " + (isDeleted ? "invisible" : "fade-in")} >
        <input type="checkbox" onChange={handleCheckboxChange} checked={task.completed ? "checked" : ""}/>
        <p className={task.completed ? "checked" : ""}>{task.content}</p>
        <img className="deleteButton" src={deleteImage} onClick={handleDelete}/>
    </div>
    );
}

export default Task;

// clients/angular-client/src/app/task/task.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';


@Component({
  selector: 'app-task',
  standalone: true,
  templateUrl: './task.component.html',
  styleUrls: ['./task.component.css']
})
export class TaskComponent {
  @Input() task: any;
  @Output() completed = new EventEmitter<number>();
  @Output() deleted = new EventEmitter<number>();

  isDeleted: boolean = false;

  constructor() {}

  handleCheckboxChange(): void {
    this.completed.emit(this.task.id);
  }

  handleDelete(): void {
    // Mutating state directly to handle rapid deletion
    this.task.deleting = true;
    this.isDeleted = true;

    setTimeout(() => {
      this.deleted.emit(this.task.id);
      console.log(this.task.id);
    }, 600);
  }
}
<div [class.invisible]="isDeleted" [class.fade-in]="!isDeleted" class="task">
    <input type="checkbox" (change)="handleCheckboxChange()" [checked]="task.completed"/>
    <p [class.checked]="task.completed">{{ task.content }}</p>
    <img class="deleteButton" src="assets/cross.png" (click)="handleDelete()" />
</div>
